name: Waka Readme

on:
  # for manual workflow trigger
  workflow_dispatch:
    schedule:
      # runs at 12 AM UTC (5:30 AM IST)
      - cron: " 0 0 * * *"

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master # this action name
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }} # required
          ### meta
          
          ### content
        SHOW_TITLE: true
        SECTION_NAME: waka
        BLOCKS: ░▒▓█
        TIME_RANGE: all_time
        SHOW_TIME: true
        SHOW_TOTAL: true
        IGNORED_LANGUAGES: YAML JSON TOML
        COMMIT_MESSAGE: Updated waka-readme graph with new metrics
        TARGET_BRANCH: main
        TARGET_PATH: README.md
        COMMITTER_NAME: GitHubActionBot
        COMMITTER_EMAIL: action-bot@github.com
        AUTHOR_NAME: Francis Njoroge Nderitu
        AUTHOR_EMAIL: iamfrsncis@gmail.com
